/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */
// ============================================================
// Supabase 프로젝트 연결 정보
// 이 파일은 Supabase 백엔드 서버에 접속하기 위한 프로젝트 ID와 공개 키를 담고 있습니다.
// 비전공자 설명: 마치 건물에 들어가기 위한 '주소'와 '방문자 출입증' 같은 정보입니다.
// ============================================================

// Supabase 프로젝트 고유 ID (프로젝트를 구분하는 식별자)
export const projectId = "vypttxusdlwevgmhtczj";

// Supabase 공개 익명 키 (인증 없이 접근 가능한 기본 API 키)
// 이 키는 클라이언트(브라우저)에서 안전하게 사용할 수 있는 공개 키입니다.
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZ5cHR0eHVzZGx3ZXZnbWh0Y3pqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjQ4MDgyOTQsImV4cCI6MjA4MDM4NDI5NH0.RJrVL2bBZW5ggL_amJhog_4nVeNUJWHXhNw9jDW5R3c";
