/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */
// ============================================================
// kv_store.tsx - Supabase KV(Key-Value) Store 래퍼
// 이 파일은 Supabase DB 테이블을 키-값 저장소처럼 사용하기 위한 함수들을 제공합니다.
// 비전공자 설명: 마치 사물함(key=번호, value=내용물)처럼, 이름(key)을 알면
// 해당 데이터(value)를 꺼내거나 저장하거나 삭제할 수 있습니다.
//
// 실제 DB 테이블 구조:
// CREATE TABLE kv_store_51087ee6 (
//   key TEXT NOT NULL PRIMARY KEY,
//   value JSONB NOT NULL
// );
//
// 테이블 확인: https://supabase.com/dashboard/project/vypttxusdlwevgmhtczj/database/tables
// ============================================================

// Supabase 클라이언트 라이브러리를 가져옵니다. (Deno 환경용)
import { createClient } from "jsr:@supabase/supabase-js@2.49.8";

// Supabase 클라이언트를 생성하는 함수
// 환경 변수에서 URL과 서비스 롤 키를 읽어 인증합니다.
// (서비스 롤 키는 서버 전용 슈퍼 권한 키입니다.)
const client = () => createClient(
  Deno.env.get("SUPABASE_URL"),
  Deno.env.get("SUPABASE_SERVICE_ROLE_KEY"),
);

// ============================================================
// set - 특정 키에 값을 저장합니다. (이미 있으면 덮어씁니다)
// key: 저장할 이름 (예: "store:iic:store-1")
// value: 저장할 데이터 (어떤 형태든 가능)
// ============================================================
export const set = async (key: string, value: any): Promise<void> => {
  const supabase = client();
  const { error } = await supabase.from("kv_store_51087ee6").upsert({
    key,
    value
  });
  // 오류가 있으면 예외를 던져서 호출하는 쪽이 알 수 있게 합니다.
  if (error) {
    throw new Error(error.message);
  }
};

// ============================================================
// get - 특정 키의 값을 가져옵니다.
// key: 가져올 이름 (예: "store:iic:store-1")
// 반환값: 저장된 데이터, 없으면 undefined
// ============================================================
export const get = async (key: string): Promise<any> => {
  const supabase = client();
  const { data, error } = await supabase
    .from("kv_store_51087ee6")
    .select("value")
    .eq("key", key)
    .maybeSingle(); // 결과가 없어도 오류를 내지 않습니다.
  if (error) {
    throw new Error(error.message);
  }
  return data?.value;
};

// ============================================================
// del - 특정 키와 그 값을 삭제합니다.
// key: 삭제할 이름 (예: "store:iic:store-1")
// ============================================================
export const del = async (key: string): Promise<void> => {
  const supabase = client();
  const { error } = await supabase
    .from("kv_store_51087ee6")
    .delete()
    .eq("key", key);
  if (error) {
    throw new Error(error.message);
  }
};

// ============================================================
// mset - 여러 키에 여러 값을 한 번에 저장합니다.
// keys: 저장할 이름 배열 (예: ["store:iic:1", "store:iic:2"])
// values: 각 이름에 저장할 데이터 배열 (keys와 순서가 일치해야 합니다)
// ============================================================
export const mset = async (keys: string[], values: any[]): Promise<void> => {
  const supabase = client();
  // keys와 values를 묶어 [{key, value}, ...] 형태로 만들어 한 번에 저장합니다.
  const { error } = await supabase
    .from("kv_store_51087ee6")
    .upsert(keys.map((k, i) => ({ key: k, value: values[i] })));
  if (error) {
    throw new Error(error.message);
  }
};

// ============================================================
// mget - 여러 키의 값을 한 번에 가져옵니다.
// keys: 가져올 이름 배열 (예: ["store:iic:1", "store:iic:2"])
// 반환값: 각 키에 해당하는 데이터 배열
// ============================================================
export const mget = async (keys: string[]): Promise<any[]> => {
  const supabase = client();
  const { data, error } = await supabase
    .from("kv_store_51087ee6")
    .select("value")
    .in("key", keys); // 여러 키를 한 번에 조회합니다.
  if (error) {
    throw new Error(error.message);
  }
  return data?.map((d) => d.value) ?? [];
};

// ============================================================
// mdel - 여러 키와 그 값들을 한 번에 삭제합니다.
// keys: 삭제할 이름 배열
// ============================================================
export const mdel = async (keys: string[]): Promise<void> => {
  const supabase = client();
  const { error } = await supabase
    .from("kv_store_51087ee6")
    .delete()
    .in("key", keys);
  if (error) {
    throw new Error(error.message);
  }
};

// ============================================================
// getByPrefix - 특정 접두사(prefix)로 시작하는 모든 항목을 가져옵니다.
// prefix: 검색할 이름 접두사 (예: "store:iic:" → "store:iic:1", "store:iic:2" 등 모두 조회)
// 반환값: 해당 접두사로 시작하는 모든 데이터 배열
// ============================================================
export const getByPrefix = async (prefix: string): Promise<any[]> => {
  const supabase = client();
  const { data, error } = await supabase
    .from("kv_store_51087ee6")
    .select("key, value")
    .like("key", prefix + "%"); // SQL LIKE로 접두사 검색합니다.
  if (error) {
    throw new Error(error.message);
  }
  return data?.map((d) => d.value) ?? [];
};
